README.md, package.json
=> Rename eslint-config-moneyforward-fukuoka to eslint-config-moneyforward

.release-it.json, package.json
for release.
https://github.com/release-it/release-it
=> Install release-it

package.json
Reverts moneyforward/eslint-config-moneyforward#21
=> Revert "Bump version 1.0.1"

.github/dependabot.yml
=> dependabot init

package-lock.json, package.json, rules/node.js
Implement the ruleset based on [recommend ruleset of eslint-plugin-n](https://github.com/eslint-community/eslint-plugin-n/blob/master/lib/configs/recommended.js).
This ruleset depends on [eslint-plugin-n](https://www.npmjs.com/package/eslint-plugin-n).
The development of [eslint-plugin-node](https://github.com/mysticatea/eslint-plugin-node) has stopped for a long time, and the use of [eslint-plugin-n](https://github.com/eslint-community/eslint-plugin-n) is currently recommended.
- #187 
- [eslint-plugin-n](https://www.npmjs.com/package/eslint-plugin-n)
- [eslint-plugin-node](https://github.com/mysticatea/eslint-plugin-node)
=> feat: Implement v3 rule "node"

package-lock.json, package.json, rules/jest-dom.js
Implement the ruleset based on [recommend ruleset of eslint-plugin-jest-dom](https://github.com/testing-library/eslint-plugin-jest-dom/tree/main?tab=readme-ov-file#supported-rules).
This ruleset depends on [eslint-plugin-jest-dom](https://github.com/testing-library/eslint-plugin-jest-dom).
- #230
- [eslint-plugin-jest-dom](https://github.com/testing-library/eslint-plugin-jest-dom)
=> feat: Implement v3 rule "jest-dom"

package-lock.json, package.json, rules/testing-library/react.js
Implement the ruleset based on [recommend ruleset of eslint-plugin-testing-library:react](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/lib/configs/react.ts)
This ruleset depends on [eslint-plugin-testing-library](https://github.com/testing-library/eslint-plugin-testing-library).
- #192 
- [eslint-plugin-testing-library](https://github.com/testing-library/eslint-plugin-testing-library)
=> feat: Implement v3 rule "testing-library"

package-lock.json, package.json, rules/storybook.js
Implement the ruleset based on [recommend ruleset (≒ configs) of eslint-plugin-storybook](https://github.com/storybookjs/eslint-plugin-storybook/blob/main/lib/configs/recommended.ts).
- [no-stories-of](https://github.com/storybookjs/eslint-plugin-storybook/blob/main/docs/rules/no-stories-of.md)
- Since Storybook 5.2, the CSF format was introduced and the storiesOf API has been deprecated.
- [no-title-property-in-meta](https://github.com/storybookjs/eslint-plugin-storybook/blob/main/docs/rules/no-title-property-in-meta.md)
- Starting in CSF 3.0, story titles can be generated automatically.
This ruleset depends on [eslint-plugin-storybook](https://github.com/storybookjs/eslint-plugin-storybook).
- #198 
- [storybookjs/eslint-plugin-storybook: …
=> feat: Implement v3 rule storybook

configs/essentials.js, rules/imports.js
- [rules/best-practices](/moneyforward/eslint-config-moneyforward/blob/main/rules/best-practices.js)
- [rules/errors](/moneyforward/eslint-config-moneyforward/blob/main/rules/errors.js)
- [rules/es6](/moneyforward/eslint-config-moneyforward/blob/main/rules/es6.js)
- [rules/imports](/moneyforward/eslint-config-moneyforward/blob/main/rules/imports.js)
- [rules/promise](/moneyforward/eslint-config-moneyforward/blob/main/rules/promise.js)
- [rules/style](/moneyforward/eslint-config-moneyforward/blob/main/rules/style.js)
- [rules/variables](/moneyforward/eslint-config-moneyforward/blob/main/rules/variables.js)
Specified the `settings` field by referring to the [imports](https://github.com/airbnb/javascript/blob/master/packages/esl …
=> feat: Implement v3 config "essentials"

configs/jsdoc.js
[rules/jsdoc](https://github.com/moneyforward/eslint-config-moneyforward/blob/main/rules/jsdoc.js)
- #201
=> feat: Implement config `jsdoc`

configs/react.js
- [rules/react](https://github.com/moneyforward/eslint-config-moneyforward/blob/main/rules/react.js)
- [rules/react-hooks](https://github.com/moneyforward/eslint-config-moneyforward/blob/main/rules/react-hooks.js)
- [rules/jsx-a11y](https://github.com/moneyforward/eslint-config-moneyforward/blob/main/rules/jsx-a11y.js)
- #204
=> feat: Implement config "react"

configs/node.js
[rules/node](https://github.com/moneyforward/eslint-config-moneyforward/blob/main/rules/node.js)
- #203
=> feat: Implement config "node"

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md
Create following templates for reporting issues.
- Bug Report
- Feature Request
It's desirable to have some templates as an aid for reporting feature requests and bug reports.
=> chore: Create Issue templates

package-lock.json, package.json, tests/snapshot-test/README.md, tests/snapshot-test/helper.js, tests/snapshot-test/next/.eslintrc.js, tests/snapshot-test/next/__snapshots__/snapshot.test.js.snap, tests/snapshot-test/next/snapshot.test.js, tests/snapshot-test/node/.eslintrc.js, tests/snapshot-test/node/__snapshots__/snapshot.test.js.snap, tests/snapshot-test/node/snapshot.test.js, tests/snapshot-test/react/.eslintrc.js, tests/snapshot-test/react/__snapshots__/snapshot.test.js.snap, tests/snapshot-test/react/snapshot.test.js, tests/snapshot-test/storybook/.eslintrc.js, tests/snapshot-test/storybook/__snapshots__/snapshot.test.js.snap, tests/snapshot-test/storybook/snapshot.test.js
Implemented a snapshot-test for verifying the integrity of the ESLint Configuration. These tests are useful for making sure that our configuration remains consistent as you go through refactorings, such as rewriting our ESLint Config as "Flat Config".
- https://github.com/moneyforward/frontend-forward/issues/156
=> test: Implement a Snapshot-test

tests/snapshot-test/next/.eslintrc.js, tests/snapshot-test/next/__snapshots__/snapshot.test.js.snap, tests/snapshot-test/node/.eslintrc.js, tests/snapshot-test/node/__snapshots__/snapshot.test.js.snap, tests/snapshot-test/node/snapshot.test.js, tests/snapshot-test/react/.eslintrc.js, tests/snapshot-test/react/__snapshots__/snapshot.test.js.snap, tests/snapshot-test/storybook/.eslintrc.js, tests/snapshot-test/storybook/__snapshots__/snapshot.test.js.snap
I forgot to update the snapshot-test logs when I deleted unnecessary rule settings in #295.
=> chore: Upate snapshot test log

README.md
With the release of v4, installation instructions for Flat Config have been added to the README.
- https://github.com/moneyforward/frontend-forward/issues/157
=> docs: Update README for v4

.github/CONTRIBUTING.md
Created a documentation to explain how anyone that considering contributing to this project can do so.
The contents of the document are written with reference to [the description in `facebook/stylex`](https://github.com/facebook/stylex/blob/main/.github/CONTRIBUTING.md) and the support of ChatGPT.
- https://github.com/moneyforward/frontend-forward/issues/77
=> docs: Write a Contributing guide

.github/PULL_REQUEST_TEMPLATE.md
Pull request templates allow you to standardize what contributors include when opening pull requests in your repository.
This template is created based on [embeddedartistry/templates/oss_docs/PULL_REQUEST_TEMPLATE.md](https://github.com/embeddedartistry/templates/blob/master/oss_docs/PULL_REQUEST_TEMPLATE.md), but in a more simplified form.
https://github.com/moneyforward/frontend-forward/issues/167
- [templates/oss_docs/PULL_REQUEST_TEMPLATE.md at master · embeddedartistry/templates](https://github.com/embeddedartistry/templates/blob/master/oss_docs/PULL_REQUEST_TEMPLATE.md)
=> chore: Create a Pull Request Template

package-lock.json, package.json, release.config.js
By adding `!` symbol after `type/scope` in the commit message, it will be recognized as an alternative to `BREAKING CHANGE:`.
Since `semantic-release` doesn't work properly with `v23.x`, I updated it to `v24.1.0` at this time.
- [semantic-release/commit-analyzer: :bulb: semantic-release plugin to analyze commits with conventional-changelog](https://github.com/semantic-release/commit-analyzer?tab=readme-ov-file#options)
- [conventional-changelog/packages/conventional-changelog-conventionalcommits at master · conventional-changelog/conventional-changelog](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-conventionalcommits)
- https://github.com/semantic-release/semantic-release/issues/2339#issuecomment-1451987883
=> ci: Recognize `!` symbol as `BREAKING CHANGE:`

release.config.js
Removed properties that can be left at their default values.
- [`branches`](https://semantic-release.gitbook.io/semantic-release/usage/configuration#branches): no need to limit the `main` branch.
- [`messages`](https://github.com/semantic-release/git?tab=readme-ov-file#options): the default setting is sufficient.
- [Configuration | semantic-release](https://semantic-release.gitbook.io/semantic-release/usage/configuration#branches)
- [semantic-release/git: :twisted_rightwards_arrows: semantic-release plugin to commit release assets to the project's git repository](https://github.com/semantic-release/git?tab=readme-ov-file#options)
=> ci: Remove unnecessary property specifications

.github/CONTRIBUTING.md
There was no instruction on what to do when opening a pull request against a branch with only one commit, which created hassle for committers. So a note has been added to the `CONTRIBUTING.md` to prevent this.
- https://github.com/moneyforward/eslint-config-moneyforward/actions/runs/10593238117
=> docs: Add a note about the format of commit messages

README.md
By listing the links to the documentation added in #328 in the `README.md`, this doc will be accessible to users.
- #328 
- #322
=> docs: Add a troubleshooting link to README

.github/CONTRIBUTING.md
=> chore: Fix typo

.github/actions/restore-node/action.yml, .github/workflows/release.yml, .github/workflows/test.yml
ci: Implement `restore-node` as composite action
The GHA configuration was redundant, so the common parts were defined as composite actions and the unnecessary parts were deleted.
- [Creating a composite action - GitHub Docs](https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action)
=> ci: Implement `restore-node` as composite action

package-lock.json, package.json
To support ESLint v9, we must update `eslint-plugin-jest` to `v28.5.0` higher.
- https://github.com/moneyforward/frontend-forward/issues/213
=> feat: Update eslint-plugin-jest version

package-lock.json, package.json
To support ESLint v9, we must update `eslint-plugin-jest-dom` to `v5.4.0` higher.
https://github.com/moneyforward/frontend-forward/issues/214
=> feat: Update eslint-plugin-jest-dom version

package-lock.json, package.json, tests/snapshot-test/eslintrc/next/__snapshots__/snapshot.test.js.snap, tests/snapshot-test/eslintrc/node/__snapshots__/snapshot.test.js.snap, tests/snapshot-test/eslintrc/react/__snapshots__/snapshot.test.js.snap, tests/snapshot-test/eslintrc/storybook/__snapshots__/snapshot.test.js.snap, tests/snapshot-test/flat/next/__snapshots__/snapshot.test.js.snap, tests/snapshot-test/flat/node/__snapshots__/snapshot.test.js.snap, tests/snapshot-test/flat/react/__snapshots__/snapshot.test.js.snap, tests/snapshot-test/flat/storybook/__snapshots__/snapshot.test.js.snap
To support ESLint v9, we must update `eslint-plugin-promise` to `v7.0.0` higher.
- https://github.com/moneyforward/frontend-forward/issues/205
=> feat!: Update eslint-plugin-promise version

package-lock.json, package.json
To support ESLint v9, we must update `eslint-plugin-n` to `v17.7.0` higher.
- https://github.com/moneyforward/frontend-forward/issues/208
=> feat: Update eslint-plugin-n version

package-lock.json, package.json
To support ESLint v9, we must update `eslint-plugin-jsx-a11y` to `v6.9.0` higher.
- https://github.com/moneyforward/frontend-forward/issues/209
=> feat: Update eslint-plugin-jsx-a11y version

package-lock.json, package.json
To support ESLint v9, we must update `eslint-plugin-react-hooks` to `v5.0.0` higher.
- https://github.com/moneyforward/frontend-forward/issues/210
=> feat!: Update eslint-plugin-react-hooks version

package-lock.json, package.json
To support ESLint v9, we must update `eslint-plugin-react` to `v7.35.0` higher.
- https://github.com/moneyforward/frontend-forward/issues/211
=> feat: Update eslint-plugin-react version

package-lock.json, package.json
To support ESLint v9, we must update `eslint-plugin-testing-library` to `v6.4.0` higher.
- https://github.com/moneyforward/frontend-forward/issues/215
=> feat!: Update eslint-plugin-testing-library version

package-lock.json, package.json
To support ESLint v9, we must update `@next/eslint-plugin-next` to `v15.0.0` higher.
- https://github.com/moneyforward/frontend-forward/issues/207
=> feat!: Update eslint-plugin-next version

packages/eslint-config/tests/snapshot-test/flat/next/__snapshots__/snapshot.test.js.snap, packages/eslint-config/tests/snapshot-test/flat/node/__snapshots__/snapshot.test.js.snap, packages/eslint-config/tests/snapshot-test/flat/react/__snapshots__/snapshot.test.js.snap, packages/eslint-config/tests/snapshot-test/flat/storybook/__snapshots__/snapshot.test.js.snap
=> chore(eslint-config): update snapshot test log
