moneyforward/frontend-tools

.github/workflows/test.yml

This is a first step for supporting eslint v8.
Run both eslint v7 and v8 on ci.
Ignore eslint v8 errors.
refs #14

Add eslint matrix on ci (with continue-on-error)

---

.github/workflows/test.yml
package.json

Be available with eslint 8
- relax dependencies for eslint 8
- detect error on eslint 8
fixes #14
for local confirmation:
```
rm package-lock.json
rm -rf ./node_modules
npm install eslint@^8.0.0
or
npm install eslint@^7.29.0
```

Be available with both eslint 7 and eslint 8

---

.github/workflows/test.yml

Node.js v12 was EOS from Jest v29
https://jestjs.io/docs/upgrading-to-jest29
We should merge also this PR.
https://github.com/moneyforward/eslint-config-moneyforward/pull/69
- remove node v12 test

EOS for Node.js v12

---

.github/workflows/check_pull_request_title.yml

Introduce a GitHub Action called [action-semantic-pull-request](https://github.com/amannn/action-semantic-pull-request) to check that the Pull Request title is in the appropriate format.
- [frontend-forward/docs/ADRs/2024-02-05-force-pull-request-title-format-for-oss.md at main · moneyforward/frontend-forward](https://github.com/moneyforward/frontend-forward/blob/main/docs/ADRs/2024-02-05-force-pull-request-title-format-for-oss.md)
- https://github.com/moneyforward/frontend-forward/issues/72

ci: Check Pull Request Title

---

rules/errors.js

Implement the ruleset by referring to the [errors](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/errors.js) of [eslint-config-airbnb-base](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base).
However, the following rule is set by us:
- [no-console](https://eslint.org/docs/latest/rules/no-console)
-  `info`, `warn`, `error`, `time`, and `timeEnd` are permitted because they are useful.
- [javascript/packages/eslint-config-airbnb-base/rules/errors.js at master · airbnb/javascript](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/errors.js)
- [Rules Reference - ESLint - Pluggable JavaScript Linter](https://eslint.org/docs/latest/rules/)
- #184

feat: Implement the rule "errors"

---

rules/es6.js

Implement the ruleset by referring to the [es6](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/es6.js) of [eslint-config-airbnb-base](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base).
- [arrow-body-style](https://eslint.org/docs/latest/rules/arrow-body-style#requirereturnforobjectliteral)
- Considering readability, set `requireReturnForObjectLiteral` to `true`.
- [no-useless-constructor](https://eslint.org/docs/rules/no-useless-constructor)
- An empty constructor method must be available in order to use TypeScript's Parameter Properties.
- [javascript/packages/eslint-config-airbnb-base/rules/es6.js at master · …

feat: Implement the rule "es6"

---

package-lock.json
package.json
rules/imports.js

Implement the ruleset by referring to the [imports](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/imports.js) of [eslint-config-airbnb-base](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base).
- [import/extensions](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/extensions.md)
- Disable it to avoid including file extensions in the import path.
- [import/prefer-default-export](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/prefer-default-export.md)
- Disable it to allow named exports.
- [import/no-default-export](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-default-export.md)
- Enable it to …

feat: Implement the rule "imports"

---

rules/style.js

Implement the ruleset by referring to the [style](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js) of [eslint-config-airbnb-base](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base).
- [func-names](https://eslint.org/docs/rules/func-names)
- Omitting the function name makes debugging difficult.
- [no-nested-ternary](https://eslint.org/docs/rules/no-nested-ternary)
- Disable it because there is no problem if you use line breaks and indentation properly.
- [no-plusplus](https://eslint.org/docs/rules/no-plusplus)
- Enable it with `allowForLoopAfterthoughts` option
Most of these rules are disabled by [eslint-config-prettier](https://github.com/prettier/eslint-config-p …

feat: Implement the rule "style"

---

rules/es6.js

This PR is a patch for fix #212.
Disable `requireReturnForObjectLiteral` in `arrow-body-style` rule. This is because if this option is enabled, `return` cannot be omitted.
```js
/*
* eslint arrow-body-style: ["error", "as-needed", {
*   "requireReturnForObjectLiteral": true
* }]
*/
const foo = () => ({ foo: 0 });           // 💥Invalid
const bar = () => { return { bar: 0 }; }; // 👍Valid
```
**TO-BE**
```js
/*
* eslint arrow-body-style: ["error", "as-needed", {
*   "requireReturnForObjectLiteral": false
* }]
*/
const foo = () => ({ foo: 0 });           // 👍Valid
const bar = () => { return { bar: 0 }; }; // 💥Invalid
```
- #212
- [arrow-body-style - ESLint - Pluggable JavaScript Linter](https://eslint.org/docs/latest/rules/arrow-body-style#requirereturnforobjectliteral)

chore: disable option `requireReturnForObjectLiteral` in `arrow-body-style`

---

package-lock.json
package.json
rules/promise.js

Implement the ruleset based on [recommend ruleset of eslint-plugin-promise](https://github.com/eslint-community/eslint-plugin-promise/blob/main/index.js#L32-L43).
- [always-return](https://github.com/eslint-community/eslint-plugin-promise/blob/main/docs/rules/always-return.md)
- In use cases that don't assume a return value, such as [`React.Suspense`](https://react.dev/reference/react/Suspense), this rule can be confusing. However, it's certainly better to return as much as possible, so only output a `warn`.
- [no-nesting](https://github.com/eslint-community/eslint-plugin-promise/blob/main/docs/rules/no-nesting.md)
- Disallowing nesting may actually increase complexity.
This ruleset depends on …

feat: Implement v3 rule "promise"

---

package-lock.json
package.json
rules/variables.js

Implement the ruleset by referring to the [variables](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/variables.js) of [eslint-config-airbnb-base](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base).
- [no-shadow](https://eslint.org/docs/rules/no-shadow)
- Disable it as it'll also warn about variables with short lifetimes, such as callback function and loop counters.
- [no-undef](https://eslint.org/docs/rules/no-undef)
- Disable it as it'll also warn about APIs that are even obvious, such as `document` and `window`.
- [no-use-before-define](https://eslint.org/docs/latest/rules/no-use-before-define)
- Disable it to give priority to writing order that takes readability into …

feat: Implement the rule "variables"

---

package-lock.json
package.json
rules/jsx-a11y.js

Implement the ruleset by referring to the [eslint-plugin-jsx-a11y:recommended](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/src/index.js#L56-L199) and the [react-a11y](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react-a11y.js) of [eslint-config-airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb).
- [autocomplete-valid](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/autocomplete-valid.md)
- the plugin recommends this rule and it's certainly useful.
- [interactive-supports-focus](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/interactive-supports-focus.md)
- We will consider enabling it in `strict …

feat: Implement v3 rule `jsx-a11y`

---

rules/react-hooks.js

Implement the ruleset as `react-hooks`.
This ruleset depends on [eslint-plugin-react-hooks](https://github.com/facebook/react/tree/main/packages/eslint-plugin-react-hooks).
- #196 
- [react/packages/eslint-plugin-react-hooks at main · facebook/react](https://github.com/facebook/react/tree/main/packages/eslint-plugin-react-hooks)

feat: Implement the rule "react-hooks"

---

package-lock.json
package.json
rules/react.js

Implement the ruleset by referring to the [eslint-plugin-react:recommended](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/configs/recommended.js) and the [react](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react.js) of [eslint-config-airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb).
- [jsx-handler-names](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-handler-names.md)
- Enable it
- [jsx-sort-props](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-sort-props.md)
- Enable it
- [jsx-uses-react](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-uses-react.md)
- Disable it …

feat: Implement v3 rule `react`

---

package-lock.json
package.json
rules/jsdoc.js

Implement the ruleset based on [recommend ruleset of eslint-plugin-jsdoc](https://github.com/gajus/eslint-plugin-jsdoc/blob/main/src/index.js#L255) and [my article written on Zenn](https://zenn.dev/wakamsha/articles/setup-eslint-plugin-jsdoc).
This ruleset depends on [eslint-plugin-jsdoc](https://github.com/gajus/eslint-plugin-jsdoc).
- #197 
- [gajus/eslint-plugin-jsdoc: JSDoc specific linting rules for ESLint.](https://github.com/gajus/eslint-plugin-jsdoc)
- [ESLint を使って JSDoc / TSDoc の記述を必須化する](https://zenn.dev/wakamsha/articles/setup-eslint-plugin-jsdoc)

feat: Implement v3 rule "jesdoc"

---

package-lock.json
package.json
rules/style.js
rules/typescript.js

Implement the ruleset based on [recommend ruleset of typescript-eslint](https://typescript-eslint.io/users/configs/#recommended-configurations).
This ruleset depends on [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint).
In #216, the option set to [`no-restricted-syntax`](https://eslint.org/docs/latest/rules/no-restricted-syntax) and [`@typescript-eslint/prefer-for-of`](https://typescript-eslint.io/rules/prefer-for-of) conflicted, so the setting for `for-of` was deleted from `no-restricted-syntax` options.
- #199 
- #216
- [typescript-eslint/typescript-eslint: ✨ Monorepo for all the tooling which enables ESLint to support TypeScript](https://github.com/typescript-eslint/typescript-eslint)
- [no-restricted-syntax - ESLint - Pluggable JavaScript …

feat: Implement v3 rule "typescript"

---

configs/storybook.js
rules/storybook.js

- [rules/storybook](https://github.com/moneyforward/eslint-config-moneyforward/blob/main/rules/storybook.js)
This config is only applied the files that match one of the following condition:
- `*.stories.@(ts|tsx|js|jsx)`
- `*.story.@(ts|tsx|js|jsx)`
- `**/.storybook/**/*.@(ts|tsx|js|jsx)`
Since Storybook related files require `default export`, disable the related rule enabled in #213 for these only.
- #205

feat: Implement v3 config "storybook"

---

configs/typescript.js
rules/typescript.js

- [rules/typescript](https://github.com/moneyforward/eslint-config-moneyforward/blob/main/rules/typescript.js)
This config is only applied the files that match the following condition:
- `*.@(ts|tsx|cts|mts)`
- #207

feat: Implement v3 config "typescript"

---

configs/next.js
rules/next.js

- [rules/next](https://github.com/moneyforward/eslint-config-moneyforward/blob/main/rules/next.js)
Since page files require default export, disable the related rule enabled in https://github.com/moneyforward/eslint-config-moneyforward/pull/213 for these only.
- #202

feat: Implement v3 config "next"

---

.eslintrc.js
configs/base.js
configs/prettier.js
package-lock.json
package.json

Uninstall the following unnecessary config files:
- `config/base`:
- this file is replaced by [`config/essentials`](https://github.com/moneyforward/eslint-config-moneyforward/blob/main/configs/essentials.js)
- `config/prettier`:
- This setting must be prepared by the user of Prettier.
Also updated the `.eslintrc` configuration for this repository.
- [Design Overview of eslint-config-moneyforward 3 · moneyforward/eslint-config-moneyforward · Discussion #182](https://github.com/moneyforward/eslint-config-moneyforward/discussions/182#:~:text=Projects%20formatting%20code%20with%20Prettier%20must%20also%20install%20eslint%2Dconfig%2Dprettier.%20By%20loading%20this%20additionally%2C%20you%20can%20disable%20ESLint%20rulesets%20that%20conflict%20with%20Prettier.)

chore: Remove unnecessary configs

---

package-lock.json
package.json

The following configuration file was exported and made available for reference by package users:
- [config/essentials](https://github.com/moneyforward/eslint-config-moneyforward/blob/main/configs/essentials.js)
- [config/jsdoc](https://github.com/moneyforward/eslint-config-moneyforward/blob/main/configs/jsdoc.js)
- [config/next](https://github.com/moneyforward/eslint-config-moneyforward/blob/main/configs/next.js)
- [config/node](https://github.com/moneyforward/eslint-config-moneyforward/blob/main/configs/node.js)
- [config/react](https://github.com/moneyforward/eslint-config-moneyforward/blob/main/configs/react.js)
- [config/storybook](https://github.com/moneyforward/eslint-config-moneyforward/blob/main/configs/storybook.js)
- [config/test/react](https://github.com/moneyforward/eslint-conf …

chore: Update package settings

---

.eslintrc.js
package-lock.json
package.json
rules/index.js
rules/prettier.js
tests/requires.test.js

The existing Unit Test [`/tests/requires.test.js`](https://github.com/moneyforward/eslint-config-moneyforward/blob/main/tests/requires.test.js) wasn't working properly, so I reimplemented it.
This test collects the paths of JavaScript files under the specified directory and checks whether they can be loaded　correctly (they can be worked `require`).
However, when I ran the test, I found that it wasn't being collected at all. This was caused by  an incorrect implementation of the recursive function, and this was corrected to make it work correctly.
```js
// AS-IS
filePaths: [
'/eslint-config-moneyforward/configs/test/react.js'
]
// TO-BE
filePaths: [
'/eslint-config-moneyforward/configs/essentials.js',
'/eslint-config-moneyforward/configs/jsdoc.js', …
```

test: Reimplement the Unit Test "requires"

---

rules/imports.js

Test files written in TypeScript aren't subject to the [`import/no-extraneous-dependencies`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md) rule.
In test code, imports of functions such as `describe`, `test`, and `it` are generally omitted. This rule was already applied to test files written VanillaJS, but it was added because TypeScript files were missing.
- #213

fix: Allow to omit importing some functions for test files written in TypeScript

---

README.md

Update the README as version 3.
Mainly, the following new contents have been added:
- How to use with Prettier
- About a LICENSE
Information about "Contrubuting" will be added when creating `CONTRIBUTING.md`.

docs: update README as version 3

---

.github/workflows/test.yml
.prettierignore

Unify the Node.js version specified for running tests in CI to the one specified in `.node-version` file.
Until now, `v14`, `v16` and `v18` were specified. However, since we're currently developing according to the version described in `.node-version` file, it should be sufficient if the test succeeds with this version.
The format of the `CHANGELOG.md` is invalid for Prettier, but since this file is generated automatically by CD ( `semantic-release` ), it is appropriate not to have Prettier check it.

ci: Fix the method of specifying the Node.js version

---

package-lock.json
package.json

Update Node.js engine requirement to `>= 18.18.0 || >= 20.0.0`. This means we are dropping support for Node 18 versions prior to `18.18.0`.
To update `@typescript-eslint` from the current `v6` to `v7`, we need to increase the minimum Node.js version to `v18.18.0`.
- #276 
- [typescript-eslint/CHANGELOG.md at main · typescript-eslint/typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/blob/main/CHANGELOG.md#700-2024-02-12)
- [feat: bump ESLint, NodeJS, and TS minimum version requirements by bradzacher · Pull Request #8377 · typescript-eslint/typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/pull/8377)

feat: Update Node.js version requirement

---

.github/workflows/test.yml
package-lock.json
package.json

Update the ESLint peer dependency requirement to `^8.56.0`. This means we are dropping support for ESLint 7, and we are also dropping support ESLint 8 versions prior to `8.56.0`.
- To update `@typescript-eslint` from the current `v6` to `v7`, we need to increase the minimum Node.js version to `v18.18.0`.
- To update `eslint-plugin-n` from the current `v16` to `v17`, we need to increase the minimum ESLint version to `v8`.
- #276 
- [typescript-eslint/CHANGELOG.md at main · typescript-eslint/typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/blob/main/CHANGELOG.md#700-2024-02-12)
- [feat: bump ESLint, NodeJS, and TS minimum version requirements by bradzacher · Pull Request #8377 · typescript-eslint/typescript-eslint](https://github.com/typescript-eslint/typescript-esli …

feat: Update ESLint version requirement

---

package-lock.json
package.json

Update the TypeScript peer dependency requirement to `>= 4.7.5 || ^5.0.0`. This means we are dropping support for TypeScript 4 versions prior to `4.7.5`.
Support typescript-eslint version to `^7.10.0`.
`v7` of typescript-eslint requires ESLint `v8.56.0` and Node.js `v18.18.0`. This update is possible because #271 and #272 change the minimum version of them.
- #276 
- [typescript-eslint/CHANGELOG.md at main · typescript-eslint/typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/blob/main/CHANGELOG.md#700-2024-02-12)
- [feat: bump ESLint, NodeJS, and TS minimum version requirements by bradzacher · Pull Request #8377 · typescript-eslint/typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/pull/8377)
- #271
- #272

feat: Update typescript-eslint version

---

package-lock.json
package.json

Support eslint-plugin-jest version to `^28.5.0` from `^27.9.0`.
- [Release v28.5.0 · jest-community/eslint-plugin-jest](https://github.com/jest-community/eslint-plugin-jest/releases/tag/v28.5.0)
- [Release v28.0.0 · jest-community/eslint-plugin-jest](https://github.com/jest-community/eslint-plugin-jest/releases/tag/v28.0.0)

feat: Update eslint-plugin-jest version

---

rules/imports.js

Storybook related files need to import devDependency modules. Therefore, we need to modify ESLint's import rule to allow this.
- #267 
- [eslint-plugin-import/docs/rules/no-extraneous-dependencies.md at main · import-js/eslint-plugin-import](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md)

fix: Allow import of devDependency modules in Storybook files

---

package-lock.json
package.json
rules/imports.js

Resolved the problem of incorrect recognition of alias path by TypeScript's Compiler Options.
- #281 
- https://github.com/import-js/eslint-plugin-import/issues/1485#issuecomment-535351922
- [eslint-import-resolver-typescript - npm](https://www.npmjs.com/package/eslint-import-resolver-typescript)

fix: Resolve the problem of incorrect recognition of alias path by TypeScript's Compiler Options

---

rules/imports.js

Flat Config support for eslint-plugin-import is not yet complete, which may cause import/namespace errors. A fix has been added to resolve this issue.
- #284 
- https://github.com/import-js/eslint-plugin-import/issues/2556#issuecomment-1419518561

fix: `import/namespace` error

---

rules/best-practices.js
rules/errors.js
rules/es6.js
rules/style.js
rules/variables.js

Remove rule settings that are deprecated as of ESLint v8.56.0 or lower.
- #282 
- [Rules Reference - ESLint - Pluggable JavaScript Linter](https://eslint.org/docs/latest/rules/#deprecated)

feat: Remove deprecated rule settings

---

package.json

Specified only those files (or folders) to upload to npmjs that users really need.
Currently, all source code in the repository has been uploaded to npmjs. Since it's a small repository, there is no impact on the installation load, but it is preferable to exclude files that are irrelevant to users, such as CI/CD-related files.
- #283

chore: Specify files to upload to npmjs

---

.github/workflows/release.yml

The release workflow was reimplemented from the existing design using GitHub Secrets to a design using GitHub App. The GitHub App is already installed in this repository, and the access token issued from it is used to run the release workflow. This should make it possible to use Branch Protection and semantic-release together.
Also, Implemented a release workflow in the GitHub Action workflow, with the trigger being [workflow_dispatch](https://docs.github.com/ja/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch). This means that it is not automatically executed every time a change is merged into the default branch, but rather at a time of the developer's choosing.
- [CD 構築 - semantic-release が Protected Branch に対し force-push できるようにする · Issue #148 · …

ci: Reimplement release workflow with GitHub App

---

package-lock.json
package.json

Add `jest` to the Peer Dependency list to prompt `eslint-config-moneyforward` users to install Jest.
`eslint-plugin-jest` is intended for use in environments where Jest is installed.
Therefore, it is advisable to check if Jest is installed when installing `eslint-config-moneyforward`.
- https://github.com/jest-community/eslint-plugin-jest/blob/main/package.json#L111

fix: Specify `jest` as a Peer Dependency

---

.prettierrc.js
configs/flat/essentials.mjs
configs/flat/index.mjs
configs/flat/jsdoc.mjs
configs/flat/next.mjs
configs/flat/node.mjs
configs/flat/react.mjs
configs/flat/storybook.mjs
configs/flat/test/react.mjs
configs/flat/typescript.mjs
package-lock.json
package.json
tests/snapshot-test/flat/next/__snapshots__/snapshot.test.js.snap
tests/snapshot-test/flat/next/eslint.config.mjs
tests/snapshot-test/flat/next/snapshot.test.js
tests/snapshot-test/flat/node/__snapshots__/snapshot.test.js.snap
tests/snapshot-test/flat/node/eslint.config.mjs
tests/snapshot-test/flat/node/snapshot.test.js
tests/snapshot-test/flat/react/__snapshots__/snapshot.test.js.snap
tests/snapshot-test/flat/react/eslint.config.mjs
tests/snapshot-test/flat/react/snapshot.test.js
tests/snapshot-test/flat/storybook/__snapshots__/snapshot.test.js.snap
tests/snapshot-test/flat/storybook/eslint.config.mjs
tests/snapshot-test/flat/storybook/snapshot.test.js

An interface to use `eslint-config-moneyforward` with Flat Config has been implemented. This allows "Flat Config" to provide the exact same rulesets provided in the eslintrc format.
Flat Config is ES Modules friendly, so `configs/flat` was implemented as ES Modules. Since `eslint-config-moneyforward` is designed as a CommonJS package, the file extension under the `configs/flat` directory is changed to `mjs`.
Flat Config Modules are implemented by referencing only the `rules` field from the files managed under the `rules/` directory and configuring the other fields in the files under the `configs/flat` directory.
All implemented Flat Config modules were designed to be consolidated in `configs/flat/index.mjs` and exported from there. This allows users to refer to all Config modules from the …

feat: Implement the Flat Config

---

docs/use/migrate-to-flat-config.md

Created an initial version of the "Migrate to Flat Config" guide.
This guideline is specific to migration to Flat Config and does not mention anything related to migration to v4.0.0.
- https://github.com/moneyforward/frontend-forward/issues/160

docs: Migrate to Flat Config

---

README.md

I found the import config for Next.js was missing in an example of README when I integrated this config into my project.
I added `next` to the import statement of the example to the same as the order of export default.
- N/A

docs: Add missing import config for Next.js to README

---

rules/react.js

The comments in [react/jsx-sort-props](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-sort-props.md) were wrong with the actual behavior.
**The behavior written in the comments:**
Props are sorted alphabetically.
**The actual behavior:**
Props are sorted in order of meaning, not alphabetically.
1. React reserved props: e.g. key, ref
2. Shorthand props: e.g. disabled
3. Others 
4. Callbacks e.g. onClick
N/A

docs: Fix comments for react/jsx-sort-props

---

configs/flat/typescript.mjs
tests/snapshot-test/flat/next/__snapshots__/snapshot.test.js.snap
tests/snapshot-test/flat/react/__snapshots__/snapshot.test.js.snap
tests/snapshot-test/flat/storybook/__snapshots__/snapshot.test.js.snap

The parsing settings for `import` and `export` in TypeScript were insufficient, so this bug will be fixed. Without this setting, `import * from` and `export * from` cannot be parsed properly.
- [import-js/eslint-plugin-import: ESLint plugin with rules that help validate proper imports.](https://github.com/import-js/eslint-plugin-import?tab=readme-ov-file#importparsers)

fix: TypeScript `import` and `export` parsing

---

README.md

The link to the LICENSE file in the README is for Airbnb's. https://github.com/iamturns/eslint-config-airbnb-typescript/blob/master/LICENSE
We have the LICENSE file in this repository, so this patch replaces the link with the file in this repository.
BTW, if this repository is based on the airbnb's code, this repository probably violates the airbnb's license. We should add the upstream copyright to the LICENSE file in this case. 
https://github.com/moneyforward/eslint-config-moneyforward/blob/main/LICENSE#L3
But I'm not sure the code originated from Airbnb. Therefore, I haven't changed the LICENSE file in this PR.
nothing

chore: Correct LICENSE link in README

---

release.config.js

By default, [only commit messages of type `feat`, `fix`, and `perf` are associated](https://github.com/semantic-release/commit-analyzer/blob/master/lib/default-release-rules.js#L10-L12) with a release.
However, it is desirable for commits of type `docs` and scope `README` or `LICENSE` to also be associated with a release, because `README.md` and `LICENSE` files are included in Node packages.
> [!important]
> This pull request has been created to allow the last updated README (#316) to be released  as the next version.
> However, that update was committed as type `chore`. It should have been committed as type `docs(README)`, so the commit message needs to be revised.
> ```diff
> - chore: Correct LICENSE link in README (#316)
> + docs(README): Correct LICENSE link in README (#316)
> ```
- …

ci: Specify release rules

---

.github/workflows/release.yml

It would be nice to be able to confirm the next version number of this package in CI/CD before releasing it to production.
To achieve this, the `dry-run` option has been implemented in the release workflow.
- [Configuration | semantic-release](https://semantic-release.gitbook.io/semantic-release/usage/configuration#dryrun)
- [Workflow syntax for GitHub Actions - GitHub Enterprise Cloud Docs](https://docs.github.com/en/enterprise-cloud@latest/actions/writing-workflows/workflow-syntax-for-github-actions#example-of-onworkflow_dispatchinputs)

ci: Implement `dry-run` option for release workflow

---

docs/troubleshooting/eslint-configuration-issue-with-non-standard-tsconfig-filenames-in-flat-config.md

The issue of parsing tsconfig.hoge.json will occur in several environment, but it is difficult to solve it in this library. So we decided to add a troubleshooting guideline for this problem.
The troubleshooting guide for #322
- #322
- [Relative TSConfig Projects with `parserOptions.project = true` | typescript-eslint](https://typescript-eslint.io/blog/parser-options-project-true/#whats-next)

docs: Add troubleshooting directory and add new document for tsconfig parser error

---

configs/flat/typescript.mjs
package-lock.json
package.json
rules/typescript.js
tests/snapshot-test/eslintrc/next/__snapshots__/snapshot.test.js.snap
tests/snapshot-test/eslintrc/react/__snapshots__/snapshot.test.js.snap
tests/snapshot-test/eslintrc/storybook/__snapshots__/snapshot.test.js.snap
tests/snapshot-test/flat/next/__snapshots__/snapshot.test.js.snap
tests/snapshot-test/flat/next/snapshot.test.js
tests/snapshot-test/flat/react/__snapshots__/snapshot.test.js.snap
tests/snapshot-test/flat/react/snapshot.test.js
tests/snapshot-test/flat/storybook/__snapshots__/snapshot.test.js.snap
tests/snapshot-test/flat/storybook/snapshot.test.js

- The TypeScript ESLint plugin has been updated from `v7.10.0` to `v8.16.0`, resulting an updated rule set.
- The required versions of Node.js and TypeScript have been updated due to the update of typescript-eslint.
- https://github.com/moneyforward/frontend-forward/issues/203
- [typescript-eslint | typescript-eslint](https://typescript-eslint.io/packages/typescript-eslint/#migrating-from-legacy-config-setups)

feat!: Update TypeScript Rules and Config to support ESLint v9

---

package-lock.json
package.json
tests/snapshot-test/eslintrc/next/__snapshots__/snapshot.test.js.snap
tests/snapshot-test/eslintrc/node/__snapshots__/snapshot.test.js.snap
tests/snapshot-test/eslintrc/react/__snapshots__/snapshot.test.js.snap
tests/snapshot-test/eslintrc/storybook/__snapshots__/snapshot.test.js.snap
tests/snapshot-test/flat/next/__snapshots__/snapshot.test.js.snap
tests/snapshot-test/flat/node/__snapshots__/snapshot.test.js.snap
tests/snapshot-test/flat/react/__snapshots__/snapshot.test.js.snap
tests/snapshot-test/flat/storybook/__snapshots__/snapshot.test.js.snap

To support ESLint v9, most plugins need to be updated. This will also change the minimum required version of ESLint.
- https://github.com/moneyforward/frontend-forward/issues/219

feat!: Update ESLint version requirements

---

configs/flat/storybook.mjs

[Files in `.storybook/` directory](https://storybook.js.org/docs/configure) must be exempt from [`import/no-default-export` rule](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-default-export.md). The `.eslintrc` config had this set properly, but the flat config was missing this setting.

fix: Disable `import/no-default-export` rule in `.storybook/` directory

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
LICENSE
packages/eslint-config/README.md
packages/eslint-config/package.json

Due to the repository name change and the move of `eslint-config-moneyforward` to a workspace under the monorepo, all hard-coded URLs must be revised.
There are no changes to the `eslint-config-moneyforward` codebase, but [the URL listed in the npm registry](https://www.npmjs.com/package/eslint-config-moneyforward) needs to be updated, so this fix will be released as a patch update.
- #363

fix(eslint-config): Fix the repository url

---

packages/eslint-config/package.json
packages/eslint-config/tests/snapshot-test/eslintrc/next/__snapshots__/snapshot.test.js.snap
packages/eslint-config/tests/snapshot-test/eslintrc/react/__snapshots__/snapshot.test.js.snap
packages/eslint-config/tests/snapshot-test/eslintrc/storybook/__snapshots__/snapshot.test.js.snap
packages/eslint-config/tests/snapshot-test/flat/next/__snapshots__/snapshot.test.js.snap
packages/eslint-config/tests/snapshot-test/flat/react/__snapshots__/snapshot.test.js.snap
packages/eslint-config/tests/snapshot-test/flat/storybook/__snapshots__/snapshot.test.js.snap
pnpm-lock.yaml

Between version `8.16.0` and `8.23.0` of typescript-eslint it may occur the following error: 
```
ESLint: 9.20.0
TypeError: Error while loading rule '@typescript-eslint/no-empty-function': Cannot read properties of undefined (reading 'allow')
...
```
To avoid this, update to the current latest version.
Btw, this modification adds new rules, but this is in the category of minor updates.

feat(eslint-config): Update `typescript-eslint` deps

---

packages/eslint-config/rules/typescript.js
packages/eslint-config/tests/snapshot-test/eslintrc/next/__snapshots__/snapshot.test.js.snap
packages/eslint-config/tests/snapshot-test/eslintrc/react/__snapshots__/snapshot.test.js.snap
packages/eslint-config/tests/snapshot-test/eslintrc/storybook/__snapshots__/snapshot.test.js.snap
packages/eslint-config/tests/snapshot-test/flat/next/__snapshots__/snapshot.test.js.snap
packages/eslint-config/tests/snapshot-test/flat/node/__snapshots__/snapshot.test.js.snap
packages/eslint-config/tests/snapshot-test/flat/react/__snapshots__/snapshot.test.js.snap
packages/eslint-config/tests/snapshot-test/flat/storybook/__snapshots__/snapshot.test.js.snap

- Added the `@typescript-eslint/no-deprecated` rule to allow the use of the `@deprecated` tag in JSDoc.
- This change is intended to permit the use of the `@deprecated` tag during the code migration phase.
- Details: [no-deprecated | typescript-eslint](https://typescript-eslint.io/rules/no-deprecated/)
- Updated snapshot tests to reflect the rule changes.
- [no-deprecated | typescript-eslint](https://typescript-eslint.io/rules/no-deprecated/)

fix(frontend): accept using `@deprecated` tag in JSDoc
